addSbtPlugin("org.scalameta" % "sbt-scalafmt"  % "2.3.0")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.6.1")
addSbtPlugin("io.spray"      % "sbt-revolver"  % "0.9.1")
addSbtPlugin("com.eed3si9n"  % "sbt-assembly"  % "0.15.0")
//addSbtPlugin("com.julianpeeters" % "sbt-avrohugger" % "2.0.0-RC22")
