version: '3'
services:
  application:
    container_name: denegee
    image: denegee:latest
    environment:
      - HTTP_PORT=8080
    ports:
      - 80:8080
    volumes:
      # verify permissions e.g. chmod 777 /vol/log/denegee
      - /vol/log/denegee:/opt/docker/log
